// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDir(arg1:string):Promise<string>;

export function CheckTermEmbed(arg1:string):Promise<string>;

export function CheckTermOriginal(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RunDebug():Promise<string>;
