// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDir(arg1) {
  return window['go']['main']['App']['CheckDir'](arg1);
}

export function CheckTermEmbed(arg1) {
  return window['go']['main']['App']['CheckTermEmbed'](arg1);
}

export function CheckTermOriginal(arg1) {
  return window['go']['main']['App']['CheckTermOriginal'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunDebug() {
  return window['go']['main']['App']['RunDebug']();
}
